apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-manifest
  title: Create App Manifest
  description: Scaffold a new app manifest folder
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Choose environment and tribe
      required:
        - env
        - tribe
        - serviceName
      properties:
        env:
          type: string
          title: Environment
          enum: [staging, production]
        tribe:
          type: string
          title: Tribe
          enum: [alpaca, coin, bank]
        serviceName:
          type: string
          title: App Name

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        cookiecutterCompat: true
        targetPath: .
        values:
          serviceName: ${{ parameters.serviceName }}

    - id: write-file
      name: Write values.yaml
      action: template:file
      input:
        path: ./templates/values.yaml.hbs
        outputPath: app/${{ parameters.env }}/stg-${{ parameters.tribe }}/${{ parameters.serviceName | upper }}/values.yaml
        values:
          serviceName: ${{ parameters.serviceName }}

  output:
    links:
      - title: Open repo
        url: https://github.com/your-org/app-manifest
