apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-manifest
  title: Create New App Manifest
  description: a new application manifest folder
spec:
  owner: team-devops
  type: service

parameters:
  - title: Choose Environment
    type: string
    enum:
      - staging
      - production
    ui:
      widget: select

  - title: Choose Tribe
    type: string
    enum:
      - alpaca
      - coin
      - bank
    ui:
      widget: select
steps:
  - id: fetch-base
    name: Clone base repo
    action: fetch:plain
    input:
      url: https://github.com/ajaib/app-manifest

  - id: create-files
    name: Write values.yaml
    action: template:file
    input:
      path: ./templates/values.yaml.hbs
      outputPath: app/${{ parameters.env }}/{{ parameters.serviceName | upper }}/values.yaml
      values:
        serviceName: ${{ parameters.serviceName }}

  - id: pr
    name: Open Pull Request
    action: publish:github
    input:
      repoUrl: github.com?repo=app-manifest&owner=ajaib
      branchName: add-${{ parameters.serviceName }}
      title: "Add app manifest for ${{ parameters.serviceName }}"
      description: "This manifest was generated via Backstage for tribe ${{ parameters.tribe }} in environment ${{ parameters.env }}"
      sourcePath: .
