---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alexander
spec:
  profile:
    displayName: Alexander Chai
    email: alexander.chai@ajaib.co.id
  memberOf: [team-devops]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-devops
  description: The DevOps team responsible for infrastructure and CI/CD.
spec:
  type: team
  profile:
    displayName: DevOps Team
    email: devops@example.com
    picture: https://example.com/devops-team-logo.png
  parent: engineering
  children:
    - team-sre
    - team-platform
  members:
    - alice
    - bob
    - charlie
    - guest
    - alexander
