apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-dpl-patch
  title: Create DPL Patch YAML
  description: Creates a deployment patch YAML file with resource values

spec:
  owner: devops
  type: service

  parameters:
    - title: Choose your environment and tribe
      required:
        - environment
        - tribe
        - component
        - cpu
        - memory
        - githubToken
      properties:
        environment:
          type: string
          title: Environment
          enum:
            - production
            - staging

        tribe:
          type: string
          title: Tribe
          enum:
            - prd-alpaca
            - prd-coin

        component:
          type: string
          title: Component name (e.g., FOREIGN-STOCK-DATA)

        cpu:
          type: string
          title: CPU request
          default: "2"

        memory:
          type: string
          title: Memory request/limit
          default: "4Gi"

        githubToken:
          type: string
          title: Define your githubToken
          default: GHP_

  steps:
    - id: generate-patch
      name: Generate DPL Patch YAML
      action: custom:create-github-folder
      input:
        environment: ${{ parameters.environment }}
        tribe: ${{ parameters.tribe }}
        component: ${{ parameters.component }}
        resources:
          cpu: ${{ parameters.cpu }}
          memory: ${{ parameters.memory }}

  output:
    links:
      - title: Open in GitHub
        url: https://github.com/ajaib/app-manifest # adjust if needed
