apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-dpl-patch
  title: Create DPL Patch Manifest
  description: Scaffold a patch deployment manifest for dpl
spec:
  owner: guest
  type: service

  parameters:
    - title: Patch Info
      required: ['env', 'tribe', 'component', 'cpuRequest', 'memoryRequest', 'memoryLimit']
      properties:
        env:
          type: string
          title: Environment
          enum: ['production', 'staging']
        tribe:
          type: string
          title: Tribe
          enum: ['prd-alpaca', 'prd-coin']
        component:
          type: string
          title: Component Name
          description: e.g., FOREIGN-STOCK-DATA
        cpuRequest:
          type: string
          title: CPU Request
          default: "2"
        memoryRequest:
          type: string
          title: Memory Request
          default: "4Gi"
        memoryLimit:
          type: string
          title: Memory Limit
          default: "4Gi"
        githubToken:
          type: string
          title: define your Github Token
          default: GHP__

  steps:
    - id: create-patch
      name: Create DPL Patch File
      action: custom:create-github-folder
      input:
        repoUrl: github.com?repo=app-manifest&owner=ajaib
        githubToken: ${{ parameters.githubToken }}
        environment: ${{ parameters.env }}
        tribe: ${{ parameters.tribe }}
        componentName: ${{ parameters.component }}
        cpuRequest: ${{ parameters.cpuRequest }}
        memoryRequest: ${{ parameters.memoryRequest }}
        memoryLimit: ${{ parameters.memoryLimit }}
        templatePath: ./templates/dpl-patch.yaml.ejs
        outputFile: dpl-patch.yaml

  output:
    text:
      - title: Success!
        content: "The patch file for ${{ parameters.component }} has been created."
