apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-github-folder
  title: Create Folder in GitHub Repo
  description: Creates a new folder (with a .keep file) inside a GitHub repo

spec:
  owner: guest
  type: service

  parameters:
    - title: GitHub Repo Info
      required:
        - repoUrl
        - folderPath
      properties:
        repoUrl:
          type: string
          title: GitHub Repo (owner/repo)
          description: The full repo, e.g. `ajaib/my-repo`
        folderPath:
          type: string
          title: Folder Path
          description: Path to the folder you want to create (e.g. `app/configs`)
        branch:
          type: string
          title: Branch
          description: Optional branch name (defaults to main)
          default: main

  steps:
    - id: create-folder
      name: Create GitHub Folder
      action: custom:create-github-folder
      input:
        repoUrl: ${{ parameters.repoUrl }}
        folderPath: ${{ parameters.folderPath }}
        branch: ${{ parameters.branch }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}

  output:
    links:
      - title: View Repo
        url: https://github.com/${{ parameters.repoUrl }}/tree/${{ parameters.branch }}/${{ parameters.folderPath }}
