apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-dpl-patch
  title: Create DPL Patch YAML
  description: Creates a deployment patch YAML file with resource values

spec:
  owner: guest
  type: service

  parameters:
    - title: Choose your environment and tribe
      required:
        - environment
        - tribe
        - component
        - cpu
        - memory
        - githubToken
      properties:
        environment:
          type: string
          title: Environment
          enum:
            - production
            - staging

        tribe:
          type: string
          title: Tribe
          enum:
            - prd-alpaca
            - prd-coin

        component:
          type: string
          title: Component name (e.g., FOREIGN-STOCK-DATA)

        cpu:
          type: string
          title: CPU request
          default: "2"

        memory:
          type: string
          title: Memory request/limit
          default: "4Gi"

        githubToken:
          type: string
          title: Define your githubToken
          default: GHP_

        previewOnly:
          type: boolean
          title: Preview files only?
          default: true

    - title: Open a PR
      properties:
        prTitle:
          type: string
          title: Pull Request Title
          default: "chore: scaffold dpl patch"
        prDescription:
          type: string
          title: Pull Request Description
          default: "Auto-generated patch manifest via Backstage template."

  steps:
    - id: generate-patch
      name: Generate DPL Patch YAML
      action: custom:create-github-folder
      input:
        githubToken: ${{ parameters.githubToken }}
        environment: ${{ parameters.environment }}
        tribe: ${{ parameters.tribe }}
        component: ${{ parameters.component }}
        resources:
          cpu: ${{ parameters.cpu }}
          memory: ${{ parameters.memory }}

    - id: generate-preview
      name: Generate manifest preview
      action: custom:generate-preview-only
      input:
        files:
          app/production/prd-coin/COIN-EXCHANGE/kustomization.yaml: |
            <%= renderKustomizationYaml(environment, tribe, component) %>
          app/production/prd-coin/COIN-EXCHANGE/patch/dpl-patch.yaml: |
            <%= renderDplPatch(component) %>
          app/production/prd-coin/COIN-EXCHANGE/patch/haproxy-patch.yaml: |
            ...
      if: "{{ parameters.previewOnly }}"
      output:
        preview:
          title: Files to be reviewed
          description: Preview of the generated files
          type: string
          copyable: true
          readOnly: true

    - id: publish-to-github
      name: Publish to GitHub PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=backstage-test&owner=alxndrchaii
        branchName: scaffold/${{ parameters.component }}-${{ parameters.environment }}
        title: ${{ parameters.prTitle }}
        description: ${{ parameters.prDescription }}
        targetPath: app
        commitMessage: "chore: create dpl-patch.yaml for ${{ parameters.component }}"
        token: ${{ parameters.githubToken }}
        update: true
      if: "{{ not parameters.previewOnly }}"

  output:
    links:
      - title: Open in GitHub
        url: https://github.com/ajaib/app-manifest # adjust if needed